import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/Header"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dennis Snellenberg • Freelance Designer & Developer",
  description: "Dennis portfolio generated by create next app for learning purposes.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
